### ISSUE TITLE
calling super() at the beginning of class breaks step 4

### ISSUE THREAD

**Issue by anilkhichar** [PolymerLabs/polymer-2-carousel#10]
> my-carousel.html

Following change is not allowing carousel to work which should not happen. Instead of calling **super()** in each individual life hook, can't we call it once inside constructor ?

`<script>

    // Extend Polymer.Element base class
    class MyCarousel extends Polymer.Element {

      constructor() {
        super();
       }
      connectedCallback() {
        // super.connectedCallback();
        this.selected = this.firstElementChild;
      }
</script>
`

**Comment by keanulee** [comment]
No - if you don't call `super` in a subclass method, then you're just overriding the superclass's implementation. Here we want the superclass's (i.e. Polymer's) implementation to run before our code.
