### ISSUE TITLE
Error in step-04 breaks the tutorial

### ISSUE THREAD

**Issue by laplix** [PolymerLabs/polymer-2-carousel#11]
I cloned the repository as indicated in the getting set up chapter
then, cd'ed in the polymer-2-carousel/work
bower install
and start following the tutorial
I did the Introducing Polymer 2.0 chapter without any problem
I then did chapter 4, Managing the Selected Image.

Refreshing localhost:8080 gave me this error:

content.js:62 Improvements: no code for http://localhost:8080/
:8080/service-worker.js:1 A bad HTTP response code (404) was received when fetching the script.
http://localhost:8080/service-worker.js Failed to load resource: net::ERR_INVALID_RESPONSE

Thinking I had made a stupid mistake, I cd'ed into the step-04 directory, did a bower install and polymer serve. 
Same error. 
Just to make sure it was totally broken, I cd'ed in all the following steps and got the same error.

I don't know enough to figure out why suddenly it's looking for a service-worker.js file.

Thank you

**Comment by mtxmomoaudio** [comment]
I dont have that issue myself, I'm having issues with the images loading after I get to step 4. When I modify the connected callback to set the property on the element instead of the attribute. 

connectedCallback() {
  super.connectedCallback();

  **this.selected = this.firstElementChild;**
}

**Comment by keanulee** [comment]
@laplix Sounds like you may have a service worker installed for the host http://localhost:8080/ (for another project, since this codelab doesn't use SWs). Try unregistering the SW from the Application tab in Dev Tools and reloading.

@mtxmomoaudio Yes, you have to modify `connectedCallback()` to set the `selected` property as mentioned in
https://codelabs.developers.google.com/codelabs/polymer-2-carousel/#3

**Comment by JEAxero** [comment]
@keanulee Thanks for making this comment: "Try unregistering the SW from the Application tab in Dev Tools and reloading."

I was seeing that error, too and didn't realize that the Service Worked installed from a different CodeLab was still sitting around. (One of the Progressive Web App CodeLabs, I think.) Once I went to Chrome DevTools "Application" tab, clicked on Service Workers, unregistered the Service Worker that was still attached, and re-loaded the page, the error went away as you predicted. Thanks!

**Comment by jrpool** [comment]
@keanulee solved my mystery, too. Thanks!
