### ISSUE TITLE
Please explain this.$ in "4. Managing the Selected Image"

### ISSUE THREAD

**Issue by ernsheong** [PolymerLabs/polymer-2-carousel#14]
https://codelabs.developers.google.com/codelabs/polymer-2-carousel/index.html?index=..%2F..%2Findex#3

Even as a web developer of some years of experience, I have not encountered this. `this.$` is an object that points to all the child IDs?

Relevant snippet:
```
this.$.prevBtn.disabled = !selected.previousElementSibling;
this.$.nextBtn.disabled = !selected.nextElementSibling;
```

**Comment by keanulee** [comment]
It's a Polymer-specific feature that gets an element in the local DOM by id (https://www.polymer-project.org/2.0/docs/devguide/dom-template#node-finding). I'll add a note to the codelab.
