### ISSUE TITLE
Deploy on local webserver

### ISSUE THREAD

**Issue by dr-jerry** [PolymerLabs/polymer-2-carousel#15]
Thanks for this introduction to polymer-2 it's really helpful, and one day I hope to be more productive with polymer than I ever was with jquery.

I went beyond this tutorial and experimented some more. So maybe this is not an polymer-2-carousel issue per se, but still it would be helpful for me and possible others?
Coming from a jquery environment and not really used to node, npm, bower, gulp, phantomjs, selenium, aws, heroku, firebase, google app engine etc,  i'm used to run my web applications from a webserver (localhost and a symlink to my workdirectory). I don't believe that `polymer serve` is meant for production?

I found `polymer build --bundle` will do the trick, and produce a deployable package for my apache or nginx. But when I connect the build directory to Webserver's documents (`sudo ln -sn ~/dev/polymer-2-carousel/work/build/default/ WebServer/Documents/carousel`) and try to access the application with http://localhost/carousel, it fails. The error manifests itself in `        this.$.prevBtn.disabled = !selected.previousElementSibling;`. selected appears to be null. And it is null because on assignment (`this.selected = this.firstElementChild;`) this.firstElementChild seems to be returning null where it should have returned the first image.

Once more I did not see this during tests with `polymer serve` only after deployment with `polymer build --bundle`

**Comment by keanulee** [comment]
There isn't anything specific with this codelab that would prevent it from being served from a static web server (where URLs map to files one-to-one). The URL you provided (http://localhost/carousel) looks like it serving a URL relative to "localhost/" (not "localhost/carousel/"), so I bet relative URLs aren't resolving properly (e.g. an import for "bower_components/polymer/polymer-element.html" is resolving to "localhost/bower_components/polymer/polymer-element.html", not "localhost/carousel/bower_components/polymer/polymer-element.html"). I would try to navigate to http://localhost/carousel/ (with trailing slash).

**Comment by dr-jerry** [comment]
Thanks for your response, I'm aware that this question is extending the tutorial and yet you take effort to answer it. I do appreciate it. 
To me it looks the browser is automatically extending it to localhost/carousel/, also, entering localhost/carousel/index.html is not fixing the issue. 
Also from what I understand of `polymer build --bundle` is that it is combining all sources file into one big file (index.html) which can be served stand-alone (without any references to other files) .
However I do see the bower_components directory in the build/default dir and the files my-mixin.html and my-carousel.html but I don't see any of them being referenced in index.html (the file I'm currentlly looking at). 
If my understanding is wrong I'm very curious te see how & where index.html is linking to its external files. Once again thank you for your time answering me.

**Comment by keanulee** [comment]
index.html imports my-carousel.html (https://github.com/PolymerLabs/polymer-2-carousel/blob/master/step-09/index.html#L20) and my-carousel.html imports polymer-element.html (https://github.com/PolymerLabs/polymer-2-carousel/blob/master/step-09/my-carousel.html#L12) and my-mixin.html (https://github.com/PolymerLabs/polymer-2-carousel/blob/master/step-09/my-carousel.html#L13)

**Comment by dr-jerry** [comment]
Yes Thanks! I'm aware of that and I do understand. The problem is however after doing a **deploy** (following [deploy](https://www.polymer-project.org/2.0/start/toolbox/deploy) and [polymer-cli docs](https://www.polymer-project.org/2.0/docs/tools/polymer-cli#build) ), and inspecting the generated index.html in /build/default/. It may also be an issue with polymer-cli?

 I know I can just symlink the working directory into the document root of my (develop) webserver. No need to run `polymer serve`. However I want to copy the package from my development machine, to my *production* machine. Without the usage of node, npm, bower and polymer-cli which I consider development tools and which I don't want to have installed on my production machine, call me old fashioned.

**Comment by keanulee** [comment]
Oh, this is actually a bug - if `<my-carousel>` is defined before it is used, then on Chrome (at least) the `connectedCallback` runs before the children of `<my-carousel>` (i.e. the `<img>` tags) are parsed and available. This does not happen without bundling since the document body is parsed before the HTML import finishes loading, but can be replicated if you put a `<script> </script>` tag after the HTML import and before the document body (which forces the HTML import to finish loading before parsing the document body).

I'll need to fix the carousel and update the codelab. Thanks for the heads up @dr-jerry

**Comment by keanulee** [comment]
Fixed in https://github.com/PolymerLabs/polymer-2-carousel/commit/0ad528b64c305cccc36bc7255059e217863f3597. Basically the fix is properly handling no children initially, then updating the `selected` property when the `slotchange` event is received.

**Comment by dr-jerry** [comment]
Thanks for your response and update. It feels like Polymer could benefit from some kind of JQuery's `document.ready` functionality.
Some considerations: I think the changes are massive (due to the step01 - step09 setup), and it will take quite some effort to update the tutorial. Also the code rewrite is not contributing to simplicity, clarity, and readability and may even scare of newcomers (evaluating Polymer). 
Maybe its worth considering leaving step01-step09 untouched and add an extra step in the tutorial for deployment and explaining the problems and solutions above?

**Comment by keanulee** [comment]
Doing the work only at `document.ready` is not robust enough - it's entirely possible for a user of `<my-carousel>` to dynamically alter its children during the runtime of the page (e.g. `document.querySelector('my-carousel').appendChild(newImage)`, so it's important to handle these cases.
