### ISSUE TITLE
Step 4: Error in where to place method

### ISSUE THREAD

**Issue by JEAxero** [PolymerLabs/polymer-2-carousel#17]
On the Step 4 page (near the top), there's mention of placement of the modified _resetConnected() method.

Currently, it says:

"In the connectedCallback() of my-carousel.html:" and then shows a callout of the modified code for _resetSelected().

But this isn't where that code fragment goes. It doesn't go **in** connectedCallback(). The _resetSelectedI() code shown is a modification of the _resetSelected() method that's in the MyCarousel class.

**Comment by keanulee** [comment]
Fixed. Thanks.
