### ISSUE TITLE
Step 5: need to update text to match new code

### ISSUE THREAD

**Issue by JEAxero** [PolymerLabs/polymer-2-carousel#18]
In Step 5, the description of the edit made to connectedCallback() in the text says:

"Let's remove the static properties getter from MyCarousel and the this.selected = ... line from connectedCallback() in my-carousel.html"

However, in the earlier step (3, I think) there is no longer a this.selected = ... line in connectedCallback().

Given the sample code in Step 5, I think the text should say to remove these 2 lines from connectedCallback() since that's what was in my-carousel and what got moved up to MyMixin:

      this.shadowRoot.addEventListener('slotchange', this._resetSelected.bind(this));
      this._resetSelected();

**Comment by keanulee** [comment]
Fixed. Thanks.
