### ISSUE TITLE
Step 5: Forgot to tell user to remove _resetSelected() from my-carousel.html

### ISSUE THREAD

**Issue by JEAxero** [PolymerLabs/polymer-2-carousel#19]
In Step 5, _resetSelected() is promoted to my-mixin.html.

However, there's nothing here to tell the user to remove it from my-carousel.html

Though it will all still work, (I didn't notice this until debugging a typo in Step 7), if the user ever wanted to make a change in my-mixin, it would never get called by my-carousel since there's no step to tell the user to add the super._resetSelected in the my-carousel or to remove it from my-carousel.

I believe the right fix is to just remove it from my-carousel since there's no need for any local logic to be added in at the my-carousel level

**Comment by keanulee** [comment]
Fixed
