### ISSUE TITLE
Step 8 lacks removal of event listeners

### ISSUE THREAD

**Issue by MajorBreakfast** [PolymerLabs/polymer-2-carousel#21]
There is no `_uninstallListeners()`. This means that the element will get additional listeners every time we attach it!

BTW that's why I really liked the `listeners` static property we had in Polymer 1.0. With it the code was briefer, DRY, and it would have prevented this bug. https://github.com/Polymer/polymer/pull/4632

**Comment by keanulee** [comment]
Alternatively (since that PR isn't merged yet), the `_installListeners` method should only be called once in `ready()`. I'll update the codelab with this. Thanks!
