### ISSUE TITLE
Use polymer-cli to Serve Your Element in Step 2 does not show proposed page.

### ISSUE THREAD

**Issue by liweiz** [PolymerLabs/polymer-2-carousel#9]
In step 2, getting set up, the last step is to use polymer-cli to serve the element. However, I could not get the page like the image shown at the bottom of that step as shown below.

![](https://codelabs.developers.google.com/codelabs/polymer-2-carousel/img/d9952a9d00a2c363.png)

What I can get is a page starting with those four pics without the text of "TODO: Implement image carousel", which is the image shown at the end of step 3 after everything done in that step. I'm confused.

Is the index.html in the work folder not the one for that step?

Thanks in advance,

Liwei

**Comment by keanulee** [comment]
If you see the 4 images instead of the text, that means the definition of the `<my-carousel>` element hasn't loaded. Did you run `bower install` and follow the previous steps of the codelab?

**Comment by liweiz** [comment]
Thanks for your reply. It turns out it only works on Chrome not on Safari Technology Preview. Is it better to add that information to step 2?
